"""Provider-neutral import framework."""

from pycrmkit.importers.base import (
    AcceptAllValidator,
    DuplicateResult,
    IdentityMapper,
    IdentityNormalizer,
    ImportDeduplicator,
    ImportMapper,
    ImportNormalizer,
    ImportPersister,
    ImportReader,
    ImportRow,
    ImportValidator,
    IterableReader,
    NoDuplicateDetector,
    PersistAction,
    PersistResult,
    ValidationIssue,
)
from pycrmkit.importers.mapping import FieldMapping, RecordMapper
from pycrmkit.importers.normalization import (
    NormalizationRule,
    Normalizer,
    RecordNormalizer,
    casefold_text,
    compose_normalizers,
    empty_text_to_none,
    strip_text,
)
from pycrmkit.importers.pipeline import ImportPipeline
from pycrmkit.importers.reports import (
    ImportReport,
    ImportRowError,
    ImportRowResult,
    ImportRowStatus,
    ImportStage,
)
from pycrmkit.importers.validation import (
    CompositeValidator,
    Predicate,
    PredicateValidator,
    RequiredFieldsValidator,
)

__all__ = [
    "AcceptAllValidator",
    "CompositeValidator",
    "DuplicateResult",
    "FieldMapping",
    "IdentityMapper",
    "IdentityNormalizer",
    "ImportDeduplicator",
    "ImportMapper",
    "ImportNormalizer",
    "ImportPersister",
    "ImportPipeline",
    "ImportReader",
    "ImportReport",
    "ImportRow",
    "ImportRowError",
    "ImportRowResult",
    "ImportRowStatus",
    "ImportStage",
    "ImportValidator",
    "IterableReader",
    "NoDuplicateDetector",
    "NormalizationRule",
    "Normalizer",
    "PersistAction",
    "PersistResult",
    "Predicate",
    "PredicateValidator",
    "RecordMapper",
    "RecordNormalizer",
    "RequiredFieldsValidator",
    "ValidationIssue",
    "casefold_text",
    "compose_normalizers",
    "empty_text_to_none",
    "strip_text",
]
