"""persistence baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 10:54:16.866990
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema to this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pycrmkit_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=511), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_activities'))
    )
    op.create_index(op.f('ix_pycrmkit_activities_external_id'), 'pycrmkit_activities', ['external_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_activities_occurred_at'), 'pycrmkit_activities', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_pycrmkit_activities_type'), 'pycrmkit_activities', ['type'], unique=False)
    op.create_table('pycrmkit_audit_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_audit_entries'))
    )
    op.create_index('ix_pycrmkit_audit_entity', 'pycrmkit_audit_entries', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_audit_entries_action'), 'pycrmkit_audit_entries', ['action'], unique=False)
    op.create_index(op.f('ix_pycrmkit_audit_entries_actor_id'), 'pycrmkit_audit_entries', ['actor_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_audit_entries_correlation_id'), 'pycrmkit_audit_entries', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_audit_entries_occurred_at'), 'pycrmkit_audit_entries', ['occurred_at'], unique=False)
    op.create_table('pycrmkit_communication_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_communication_intents')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_pycrmkit_communication_intents_idempotency_key'))
    )
    op.create_index(op.f('ix_pycrmkit_communication_intents_channel'), 'pycrmkit_communication_intents', ['channel'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_intents_status'), 'pycrmkit_communication_intents', ['status'], unique=False)
    op.create_table('pycrmkit_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=511), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_contacts'))
    )
    op.create_index(op.f('ix_pycrmkit_contacts_archived_at'), 'pycrmkit_contacts', ['archived_at'], unique=False)
    op.create_index(op.f('ix_pycrmkit_contacts_owner_id'), 'pycrmkit_contacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_contacts_status'), 'pycrmkit_contacts', ['status'], unique=False)
    op.create_table('pycrmkit_custom_field_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=511), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('applies_to', sa.JSON(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('reference_kinds', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'schema_version', name=op.f('pk_pycrmkit_custom_field_definitions'))
    )
    op.create_index('ix_pycrmkit_custom_field_definition_key_revision', 'pycrmkit_custom_field_definitions', ['key', 'schema_version'], unique=True)
    op.create_index(op.f('ix_pycrmkit_custom_field_definitions_active'), 'pycrmkit_custom_field_definitions', ['active'], unique=False)
    op.create_index(op.f('ix_pycrmkit_custom_field_definitions_key'), 'pycrmkit_custom_field_definitions', ['key'], unique=False)
    op.create_table('pycrmkit_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=511), nullable=False),
    sa.Column('trading_name', sa.String(length=511), nullable=True),
    sa.Column('display_name', sa.String(length=511), nullable=True),
    sa.Column('registration_number', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_organizations'))
    )
    op.create_index(op.f('ix_pycrmkit_organizations_archived_at'), 'pycrmkit_organizations', ['archived_at'], unique=False)
    op.create_index(op.f('ix_pycrmkit_organizations_legal_name'), 'pycrmkit_organizations', ['legal_name'], unique=False)
    op.create_index(op.f('ix_pycrmkit_organizations_owner_id'), 'pycrmkit_organizations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_organizations_registration_number'), 'pycrmkit_organizations', ['registration_number'], unique=False)
    op.create_index(op.f('ix_pycrmkit_organizations_status'), 'pycrmkit_organizations', ['status'], unique=False)
    op.create_index(op.f('ix_pycrmkit_organizations_tax_id'), 'pycrmkit_organizations', ['tax_id'], unique=False)
    op.create_table('pycrmkit_pipelines',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=511), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_pipelines'))
    )
    op.create_table('pycrmkit_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=128), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_relationships'))
    )
    op.create_index(op.f('ix_pycrmkit_relationships_relationship_type'), 'pycrmkit_relationships', ['relationship_type'], unique=False)
    op.create_index('ix_pycrmkit_relationships_source', 'pycrmkit_relationships', ['source_kind', 'source_id'], unique=False)
    op.create_index('ix_pycrmkit_relationships_target', 'pycrmkit_relationships', ['target_kind', 'target_id'], unique=False)
    op.create_table('pycrmkit_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_tags')),
    sa.UniqueConstraint('normalized_name', name='uq_pycrmkit_tags_normalized_name')
    )
    op.create_table('pycrmkit_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=511), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('assignee_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_tasks'))
    )
    op.create_index(op.f('ix_pycrmkit_tasks_assignee_id'), 'pycrmkit_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_tasks_due_at'), 'pycrmkit_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_pycrmkit_tasks_external_id'), 'pycrmkit_tasks', ['external_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_tasks_owner_id'), 'pycrmkit_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_tasks_priority'), 'pycrmkit_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_pycrmkit_tasks_status'), 'pycrmkit_tasks', ['status'], unique=False)
    op.create_table('pycrmkit_timeline_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id_type', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=511), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_timeline_entries')),
    sa.UniqueConstraint('source_event_id', name=op.f('uq_pycrmkit_timeline_entries_source_event_id'))
    )
    op.create_index('ix_pycrmkit_timeline_entity', 'pycrmkit_timeline_entries', ['entity_kind', 'entity_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_timeline_entries_actor_id'), 'pycrmkit_timeline_entries', ['actor_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_timeline_entries_correlation_id'), 'pycrmkit_timeline_entries', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_timeline_entries_event_type'), 'pycrmkit_timeline_entries', ['event_type'], unique=False)
    op.create_index(op.f('ix_pycrmkit_timeline_entries_kind'), 'pycrmkit_timeline_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_pycrmkit_timeline_entries_occurred_at'), 'pycrmkit_timeline_entries', ['occurred_at'], unique=False)
    op.create_table('pycrmkit_webhook_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('signing_secret', sa.String(length=255), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_webhook_subscriptions'))
    )
    op.create_index(op.f('ix_pycrmkit_webhook_subscriptions_disabled_at'), 'pycrmkit_webhook_subscriptions', ['disabled_at'], unique=False)
    op.create_table('pycrmkit_activity_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['pycrmkit_activities.id'], name=op.f('fk_pycrmkit_activity_participants_activity_id_pycrmkit_activities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_activity_participants'))
    )
    op.create_index(op.f('ix_pycrmkit_activity_participants_activity_id'), 'pycrmkit_activity_participants', ['activity_id'], unique=False)
    op.create_index('ix_pycrmkit_activity_participants_entity', 'pycrmkit_activity_participants', ['entity_kind', 'entity_id'], unique=False)
    op.create_table('pycrmkit_activity_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['pycrmkit_activities.id'], name=op.f('fk_pycrmkit_activity_references_activity_id_pycrmkit_activities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_activity_references'))
    )
    op.create_index(op.f('ix_pycrmkit_activity_references_activity_id'), 'pycrmkit_activity_references', ['activity_id'], unique=False)
    op.create_index('ix_pycrmkit_activity_references_entity', 'pycrmkit_activity_references', ['entity_kind', 'entity_id'], unique=False)
    op.create_table('pycrmkit_communication_intent_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['pycrmkit_communication_intents.id'], name=op.f('fk_pycrmkit_communication_intent_references_intent_id_pycrmkit_communication_intents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_communication_intent_references'))
    )
    op.create_index(op.f('ix_pycrmkit_communication_intent_references_intent_id'), 'pycrmkit_communication_intent_references', ['intent_id'], unique=False)
    op.create_table('pycrmkit_communication_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=511), nullable=False),
    sa.Column('normalized', sa.String(length=511), nullable=False),
    sa.Column('display_name', sa.String(length=511), nullable=True),
    sa.Column('reference_kind', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['pycrmkit_communication_intents.id'], name=op.f('fk_pycrmkit_communication_recipients_intent_id_pycrmkit_communication_intents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_communication_recipients'))
    )
    op.create_index(op.f('ix_pycrmkit_communication_recipients_intent_id'), 'pycrmkit_communication_recipients', ['intent_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_recipients_normalized'), 'pycrmkit_communication_recipients', ['normalized'], unique=False)
    op.create_table('pycrmkit_contact_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('line1', sa.String(length=511), nullable=False),
    sa.Column('line2', sa.String(length=511), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['pycrmkit_contacts.id'], name=op.f('fk_pycrmkit_contact_addresses_contact_id_pycrmkit_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_contact_addresses'))
    )
    op.create_index(op.f('ix_pycrmkit_contact_addresses_contact_id'), 'pycrmkit_contact_addresses', ['contact_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_contact_addresses_country_code'), 'pycrmkit_contact_addresses', ['country_code'], unique=False)
    op.create_table('pycrmkit_contact_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('normalized', sa.String(length=320), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verification', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['pycrmkit_contacts.id'], name=op.f('fk_pycrmkit_contact_emails_contact_id_pycrmkit_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_contact_emails'))
    )
    op.create_index(op.f('ix_pycrmkit_contact_emails_contact_id'), 'pycrmkit_contact_emails', ['contact_id'], unique=False)
    op.create_index('ix_pycrmkit_contact_emails_contact_position', 'pycrmkit_contact_emails', ['contact_id', 'position'], unique=False)
    op.create_index(op.f('ix_pycrmkit_contact_emails_normalized'), 'pycrmkit_contact_emails', ['normalized'], unique=False)
    op.create_table('pycrmkit_contact_phones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('normalized', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verification', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['pycrmkit_contacts.id'], name=op.f('fk_pycrmkit_contact_phones_contact_id_pycrmkit_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_contact_phones'))
    )
    op.create_index(op.f('ix_pycrmkit_contact_phones_contact_id'), 'pycrmkit_contact_phones', ['contact_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_contact_phones_normalized'), 'pycrmkit_contact_phones', ['normalized'], unique=False)
    op.create_table('pycrmkit_custom_field_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('definition_id', sa.String(length=36), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['definition_id', 'schema_version'], ['pycrmkit_custom_field_definitions.id', 'pycrmkit_custom_field_definitions.schema_version'], name=op.f('fk_pycrmkit_custom_field_values_definition_id_pycrmkit_custom_field_definitions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_custom_field_values'))
    )
    op.create_index('ix_pycrmkit_custom_field_value_current', 'pycrmkit_custom_field_values', ['definition_id', 'entity_kind', 'entity_id'], unique=True)
    op.create_index(op.f('ix_pycrmkit_custom_field_values_definition_id'), 'pycrmkit_custom_field_values', ['definition_id'], unique=False)
    op.create_index('ix_pycrmkit_custom_field_values_entity', 'pycrmkit_custom_field_values', ['entity_kind', 'entity_id'], unique=False)
    op.create_table('pycrmkit_delivery_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('failure_code', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['pycrmkit_communication_intents.id'], name=op.f('fk_pycrmkit_delivery_attempts_intent_id_pycrmkit_communication_intents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_delivery_attempts'))
    )
    op.create_index('ix_pycrmkit_delivery_attempt_intent_number', 'pycrmkit_delivery_attempts', ['intent_id', 'attempt_number'], unique=True)
    op.create_index(op.f('ix_pycrmkit_delivery_attempts_intent_id'), 'pycrmkit_delivery_attempts', ['intent_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_delivery_attempts_provider'), 'pycrmkit_delivery_attempts', ['provider'], unique=False)
    op.create_index(op.f('ix_pycrmkit_delivery_attempts_provider_message_id'), 'pycrmkit_delivery_attempts', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_delivery_attempts_status'), 'pycrmkit_delivery_attempts', ['status'], unique=False)
    op.create_table('pycrmkit_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('converted_opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('conversion_idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('conversion_request_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['pycrmkit_contacts.id'], name=op.f('fk_pycrmkit_leads_contact_id_pycrmkit_contacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['pycrmkit_organizations.id'], name=op.f('fk_pycrmkit_leads_organization_id_pycrmkit_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_leads')),
    sa.UniqueConstraint('conversion_idempotency_key', name=op.f('uq_pycrmkit_leads_conversion_idempotency_key'))
    )
    op.create_index(op.f('ix_pycrmkit_leads_contact_id'), 'pycrmkit_leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_leads_converted_opportunity_id'), 'pycrmkit_leads', ['converted_opportunity_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_leads_organization_id'), 'pycrmkit_leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_leads_status'), 'pycrmkit_leads', ['status'], unique=False)
    op.create_table('pycrmkit_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=511), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('stage_id', sa.String(length=255), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('probability', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['pycrmkit_contacts.id'], name=op.f('fk_pycrmkit_opportunities_contact_id_pycrmkit_contacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['pycrmkit_organizations.id'], name=op.f('fk_pycrmkit_opportunities_organization_id_pycrmkit_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_opportunities'))
    )
    op.create_index(op.f('ix_pycrmkit_opportunities_contact_id'), 'pycrmkit_opportunities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_opportunities_organization_id'), 'pycrmkit_opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_opportunities_owner_id'), 'pycrmkit_opportunities', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_opportunities_pipeline_id'), 'pycrmkit_opportunities', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_opportunities_stage_id'), 'pycrmkit_opportunities', ['stage_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_opportunities_status'), 'pycrmkit_opportunities', ['status'], unique=False)
    op.create_table('pycrmkit_organization_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('line1', sa.String(length=511), nullable=False),
    sa.Column('line2', sa.String(length=511), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pycrmkit_organizations.id'], name=op.f('fk_pycrmkit_organization_addresses_organization_id_pycrmkit_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_organization_addresses'))
    )
    op.create_index(op.f('ix_pycrmkit_organization_addresses_country_code'), 'pycrmkit_organization_addresses', ['country_code'], unique=False)
    op.create_index(op.f('ix_pycrmkit_organization_addresses_organization_id'), 'pycrmkit_organization_addresses', ['organization_id'], unique=False)
    op.create_table('pycrmkit_organization_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.Column('normalized', sa.String(length=253), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pycrmkit_organizations.id'], name=op.f('fk_pycrmkit_organization_domains_organization_id_pycrmkit_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_organization_domains'))
    )
    op.create_index(op.f('ix_pycrmkit_organization_domains_normalized'), 'pycrmkit_organization_domains', ['normalized'], unique=False)
    op.create_index(op.f('ix_pycrmkit_organization_domains_organization_id'), 'pycrmkit_organization_domains', ['organization_id'], unique=False)
    op.create_table('pycrmkit_pipeline_stages',
    sa.Column('pipeline_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=511), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('default_probability', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('terminal', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pycrmkit_pipelines.id'], name=op.f('fk_pycrmkit_pipeline_stages_pipeline_id_pycrmkit_pipelines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_id', 'id', name=op.f('pk_pycrmkit_pipeline_stages'))
    )
    op.create_table('pycrmkit_pipeline_transitions',
    sa.Column('pipeline_id', sa.String(length=255), nullable=False),
    sa.Column('from_stage', sa.String(length=255), nullable=False),
    sa.Column('to_stage', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pycrmkit_pipelines.id'], name=op.f('fk_pycrmkit_pipeline_transitions_pipeline_id_pycrmkit_pipelines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_id', 'from_stage', 'to_stage', name=op.f('pk_pycrmkit_pipeline_transitions'))
    )
    op.create_table('pycrmkit_tag_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['pycrmkit_tags.id'], name=op.f('fk_pycrmkit_tag_assignments_tag_id_pycrmkit_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_tag_assignments')),
    sa.UniqueConstraint('tag_id', 'entity_kind', 'entity_id', name='uq_pycrmkit_tag_assignments_target')
    )
    op.create_index('ix_pycrmkit_tag_assignments_entity', 'pycrmkit_tag_assignments', ['entity_kind', 'entity_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_tag_assignments_tag_id'), 'pycrmkit_tag_assignments', ['tag_id'], unique=False)
    op.create_table('pycrmkit_task_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['pycrmkit_tasks.id'], name=op.f('fk_pycrmkit_task_references_task_id_pycrmkit_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_task_references'))
    )
    op.create_index('ix_pycrmkit_task_references_entity', 'pycrmkit_task_references', ['entity_kind', 'entity_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_task_references_task_id'), 'pycrmkit_task_references', ['task_id'], unique=False)
    op.create_table('pycrmkit_timeline_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['pycrmkit_timeline_entries.id'], name=op.f('fk_pycrmkit_timeline_references_entry_id_pycrmkit_timeline_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_timeline_references'))
    )
    op.create_index('ix_pycrmkit_timeline_reference_entity', 'pycrmkit_timeline_references', ['entity_kind', 'entity_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_timeline_references_entry_id'), 'pycrmkit_timeline_references', ['entry_id'], unique=False)
    op.create_table('pycrmkit_webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['pycrmkit_webhook_subscriptions.id'], name=op.f('fk_pycrmkit_webhook_deliveries_subscription_id_pycrmkit_webhook_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_webhook_deliveries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_pycrmkit_webhook_deliveries_idempotency_key'))
    )
    op.create_index(op.f('ix_pycrmkit_webhook_deliveries_event_id'), 'pycrmkit_webhook_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_webhook_deliveries_event_type'), 'pycrmkit_webhook_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_pycrmkit_webhook_deliveries_next_attempt_at'), 'pycrmkit_webhook_deliveries', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_pycrmkit_webhook_deliveries_state'), 'pycrmkit_webhook_deliveries', ['state'], unique=False)
    op.create_index(op.f('ix_pycrmkit_webhook_deliveries_subscription_id'), 'pycrmkit_webhook_deliveries', ['subscription_id'], unique=False)
    op.create_index('ix_pycrmkit_webhook_delivery_subscription_event', 'pycrmkit_webhook_deliveries', ['subscription_id', 'event_id'], unique=True)
    op.create_table('pycrmkit_webhook_subscription_events',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['pycrmkit_webhook_subscriptions.id'], name=op.f('fk_pycrmkit_webhook_subscription_events_subscription_id_pycrmkit_webhook_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'event_type', name=op.f('pk_pycrmkit_webhook_subscription_events'))
    )
    op.create_index(op.f('ix_pycrmkit_webhook_subscription_events_event_type'), 'pycrmkit_webhook_subscription_events', ['event_type'], unique=False)
    op.create_table('pycrmkit_communication_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('intent_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.String(length=32), nullable=True),
    sa.Column('last_delivery_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_attempt_id'], ['pycrmkit_delivery_attempts.id'], name=op.f('fk_pycrmkit_communication_records_delivery_attempt_id_pycrmkit_delivery_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intent_id'], ['pycrmkit_communication_intents.id'], name=op.f('fk_pycrmkit_communication_records_intent_id_pycrmkit_communication_intents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_communication_records'))
    )
    op.create_index(op.f('ix_pycrmkit_communication_records_channel'), 'pycrmkit_communication_records', ['channel'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_records_delivery_attempt_id'), 'pycrmkit_communication_records', ['delivery_attempt_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_records_delivery_status'), 'pycrmkit_communication_records', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_records_external_id'), 'pycrmkit_communication_records', ['external_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_records_intent_id'), 'pycrmkit_communication_records', ['intent_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_records_occurred_at'), 'pycrmkit_communication_records', ['occurred_at'], unique=False)
    op.create_table('pycrmkit_email_delivery_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('recipient_channel', sa.String(length=32), nullable=True),
    sa.Column('recipient_value', sa.String(length=511), nullable=True),
    sa.Column('recipient_normalized', sa.String(length=511), nullable=True),
    sa.Column('failure_code', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_attempt_id'], ['pycrmkit_delivery_attempts.id'], name=op.f('fk_pycrmkit_email_delivery_events_delivery_attempt_id_pycrmkit_delivery_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intent_id'], ['pycrmkit_communication_intents.id'], name=op.f('fk_pycrmkit_email_delivery_events_intent_id_pycrmkit_communication_intents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_email_delivery_events'))
    )
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_delivery_attempt_id'), 'pycrmkit_email_delivery_events', ['delivery_attempt_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_event_type'), 'pycrmkit_email_delivery_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_external_event_id'), 'pycrmkit_email_delivery_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_intent_id'), 'pycrmkit_email_delivery_events', ['intent_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_occurred_at'), 'pycrmkit_email_delivery_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_provider'), 'pycrmkit_email_delivery_events', ['provider'], unique=False)
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_provider_message_id'), 'pycrmkit_email_delivery_events', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_email_delivery_events_recipient_normalized'), 'pycrmkit_email_delivery_events', ['recipient_normalized'], unique=False)
    op.create_table('pycrmkit_webhook_delivery_attempts',
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['pycrmkit_webhook_deliveries.id'], name=op.f('fk_pycrmkit_webhook_delivery_attempts_delivery_id_pycrmkit_webhook_deliveries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delivery_id', 'attempt_number', name=op.f('pk_pycrmkit_webhook_delivery_attempts'))
    )
    op.create_table('pycrmkit_communication_counterparties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=511), nullable=False),
    sa.Column('normalized', sa.String(length=511), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['pycrmkit_communication_records.id'], name=op.f('fk_pycrmkit_communication_counterparties_record_id_pycrmkit_communication_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_communication_counterparties'))
    )
    op.create_index(op.f('ix_pycrmkit_communication_counterparties_normalized'), 'pycrmkit_communication_counterparties', ['normalized'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_counterparties_record_id'), 'pycrmkit_communication_counterparties', ['record_id'], unique=False)
    op.create_table('pycrmkit_communication_record_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['pycrmkit_communication_records.id'], name=op.f('fk_pycrmkit_communication_record_references_record_id_pycrmkit_communication_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pycrmkit_communication_record_references'))
    )
    op.create_index('ix_pycrmkit_communication_record_ref_entity', 'pycrmkit_communication_record_references', ['entity_kind', 'entity_id'], unique=False)
    op.create_index(op.f('ix_pycrmkit_communication_record_references_record_id'), 'pycrmkit_communication_record_references', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema from this revision."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pycrmkit_communication_record_references_record_id'), table_name='pycrmkit_communication_record_references')
    op.drop_index('ix_pycrmkit_communication_record_ref_entity', table_name='pycrmkit_communication_record_references')
    op.drop_table('pycrmkit_communication_record_references')
    op.drop_index(op.f('ix_pycrmkit_communication_counterparties_record_id'), table_name='pycrmkit_communication_counterparties')
    op.drop_index(op.f('ix_pycrmkit_communication_counterparties_normalized'), table_name='pycrmkit_communication_counterparties')
    op.drop_table('pycrmkit_communication_counterparties')
    op.drop_table('pycrmkit_webhook_delivery_attempts')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_recipient_normalized'), table_name='pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_provider_message_id'), table_name='pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_provider'), table_name='pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_occurred_at'), table_name='pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_intent_id'), table_name='pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_external_event_id'), table_name='pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_event_type'), table_name='pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_email_delivery_events_delivery_attempt_id'), table_name='pycrmkit_email_delivery_events')
    op.drop_table('pycrmkit_email_delivery_events')
    op.drop_index(op.f('ix_pycrmkit_communication_records_occurred_at'), table_name='pycrmkit_communication_records')
    op.drop_index(op.f('ix_pycrmkit_communication_records_intent_id'), table_name='pycrmkit_communication_records')
    op.drop_index(op.f('ix_pycrmkit_communication_records_external_id'), table_name='pycrmkit_communication_records')
    op.drop_index(op.f('ix_pycrmkit_communication_records_delivery_status'), table_name='pycrmkit_communication_records')
    op.drop_index(op.f('ix_pycrmkit_communication_records_delivery_attempt_id'), table_name='pycrmkit_communication_records')
    op.drop_index(op.f('ix_pycrmkit_communication_records_channel'), table_name='pycrmkit_communication_records')
    op.drop_table('pycrmkit_communication_records')
    op.drop_index(op.f('ix_pycrmkit_webhook_subscription_events_event_type'), table_name='pycrmkit_webhook_subscription_events')
    op.drop_table('pycrmkit_webhook_subscription_events')
    op.drop_index('ix_pycrmkit_webhook_delivery_subscription_event', table_name='pycrmkit_webhook_deliveries')
    op.drop_index(op.f('ix_pycrmkit_webhook_deliveries_subscription_id'), table_name='pycrmkit_webhook_deliveries')
    op.drop_index(op.f('ix_pycrmkit_webhook_deliveries_state'), table_name='pycrmkit_webhook_deliveries')
    op.drop_index(op.f('ix_pycrmkit_webhook_deliveries_next_attempt_at'), table_name='pycrmkit_webhook_deliveries')
    op.drop_index(op.f('ix_pycrmkit_webhook_deliveries_event_type'), table_name='pycrmkit_webhook_deliveries')
    op.drop_index(op.f('ix_pycrmkit_webhook_deliveries_event_id'), table_name='pycrmkit_webhook_deliveries')
    op.drop_table('pycrmkit_webhook_deliveries')
    op.drop_index(op.f('ix_pycrmkit_timeline_references_entry_id'), table_name='pycrmkit_timeline_references')
    op.drop_index('ix_pycrmkit_timeline_reference_entity', table_name='pycrmkit_timeline_references')
    op.drop_table('pycrmkit_timeline_references')
    op.drop_index(op.f('ix_pycrmkit_task_references_task_id'), table_name='pycrmkit_task_references')
    op.drop_index('ix_pycrmkit_task_references_entity', table_name='pycrmkit_task_references')
    op.drop_table('pycrmkit_task_references')
    op.drop_index(op.f('ix_pycrmkit_tag_assignments_tag_id'), table_name='pycrmkit_tag_assignments')
    op.drop_index('ix_pycrmkit_tag_assignments_entity', table_name='pycrmkit_tag_assignments')
    op.drop_table('pycrmkit_tag_assignments')
    op.drop_table('pycrmkit_pipeline_transitions')
    op.drop_table('pycrmkit_pipeline_stages')
    op.drop_index(op.f('ix_pycrmkit_organization_domains_organization_id'), table_name='pycrmkit_organization_domains')
    op.drop_index(op.f('ix_pycrmkit_organization_domains_normalized'), table_name='pycrmkit_organization_domains')
    op.drop_table('pycrmkit_organization_domains')
    op.drop_index(op.f('ix_pycrmkit_organization_addresses_organization_id'), table_name='pycrmkit_organization_addresses')
    op.drop_index(op.f('ix_pycrmkit_organization_addresses_country_code'), table_name='pycrmkit_organization_addresses')
    op.drop_table('pycrmkit_organization_addresses')
    op.drop_index(op.f('ix_pycrmkit_opportunities_status'), table_name='pycrmkit_opportunities')
    op.drop_index(op.f('ix_pycrmkit_opportunities_stage_id'), table_name='pycrmkit_opportunities')
    op.drop_index(op.f('ix_pycrmkit_opportunities_pipeline_id'), table_name='pycrmkit_opportunities')
    op.drop_index(op.f('ix_pycrmkit_opportunities_owner_id'), table_name='pycrmkit_opportunities')
    op.drop_index(op.f('ix_pycrmkit_opportunities_organization_id'), table_name='pycrmkit_opportunities')
    op.drop_index(op.f('ix_pycrmkit_opportunities_contact_id'), table_name='pycrmkit_opportunities')
    op.drop_table('pycrmkit_opportunities')
    op.drop_index(op.f('ix_pycrmkit_leads_status'), table_name='pycrmkit_leads')
    op.drop_index(op.f('ix_pycrmkit_leads_organization_id'), table_name='pycrmkit_leads')
    op.drop_index(op.f('ix_pycrmkit_leads_converted_opportunity_id'), table_name='pycrmkit_leads')
    op.drop_index(op.f('ix_pycrmkit_leads_contact_id'), table_name='pycrmkit_leads')
    op.drop_table('pycrmkit_leads')
    op.drop_index(op.f('ix_pycrmkit_delivery_attempts_status'), table_name='pycrmkit_delivery_attempts')
    op.drop_index(op.f('ix_pycrmkit_delivery_attempts_provider_message_id'), table_name='pycrmkit_delivery_attempts')
    op.drop_index(op.f('ix_pycrmkit_delivery_attempts_provider'), table_name='pycrmkit_delivery_attempts')
    op.drop_index(op.f('ix_pycrmkit_delivery_attempts_intent_id'), table_name='pycrmkit_delivery_attempts')
    op.drop_index('ix_pycrmkit_delivery_attempt_intent_number', table_name='pycrmkit_delivery_attempts')
    op.drop_table('pycrmkit_delivery_attempts')
    op.drop_index('ix_pycrmkit_custom_field_values_entity', table_name='pycrmkit_custom_field_values')
    op.drop_index(op.f('ix_pycrmkit_custom_field_values_definition_id'), table_name='pycrmkit_custom_field_values')
    op.drop_index('ix_pycrmkit_custom_field_value_current', table_name='pycrmkit_custom_field_values')
    op.drop_table('pycrmkit_custom_field_values')
    op.drop_index(op.f('ix_pycrmkit_contact_phones_normalized'), table_name='pycrmkit_contact_phones')
    op.drop_index(op.f('ix_pycrmkit_contact_phones_contact_id'), table_name='pycrmkit_contact_phones')
    op.drop_table('pycrmkit_contact_phones')
    op.drop_index(op.f('ix_pycrmkit_contact_emails_normalized'), table_name='pycrmkit_contact_emails')
    op.drop_index('ix_pycrmkit_contact_emails_contact_position', table_name='pycrmkit_contact_emails')
    op.drop_index(op.f('ix_pycrmkit_contact_emails_contact_id'), table_name='pycrmkit_contact_emails')
    op.drop_table('pycrmkit_contact_emails')
    op.drop_index(op.f('ix_pycrmkit_contact_addresses_country_code'), table_name='pycrmkit_contact_addresses')
    op.drop_index(op.f('ix_pycrmkit_contact_addresses_contact_id'), table_name='pycrmkit_contact_addresses')
    op.drop_table('pycrmkit_contact_addresses')
    op.drop_index(op.f('ix_pycrmkit_communication_recipients_normalized'), table_name='pycrmkit_communication_recipients')
    op.drop_index(op.f('ix_pycrmkit_communication_recipients_intent_id'), table_name='pycrmkit_communication_recipients')
    op.drop_table('pycrmkit_communication_recipients')
    op.drop_index(op.f('ix_pycrmkit_communication_intent_references_intent_id'), table_name='pycrmkit_communication_intent_references')
    op.drop_table('pycrmkit_communication_intent_references')
    op.drop_index('ix_pycrmkit_activity_references_entity', table_name='pycrmkit_activity_references')
    op.drop_index(op.f('ix_pycrmkit_activity_references_activity_id'), table_name='pycrmkit_activity_references')
    op.drop_table('pycrmkit_activity_references')
    op.drop_index('ix_pycrmkit_activity_participants_entity', table_name='pycrmkit_activity_participants')
    op.drop_index(op.f('ix_pycrmkit_activity_participants_activity_id'), table_name='pycrmkit_activity_participants')
    op.drop_table('pycrmkit_activity_participants')
    op.drop_index(op.f('ix_pycrmkit_webhook_subscriptions_disabled_at'), table_name='pycrmkit_webhook_subscriptions')
    op.drop_table('pycrmkit_webhook_subscriptions')
    op.drop_index(op.f('ix_pycrmkit_timeline_entries_occurred_at'), table_name='pycrmkit_timeline_entries')
    op.drop_index(op.f('ix_pycrmkit_timeline_entries_kind'), table_name='pycrmkit_timeline_entries')
    op.drop_index(op.f('ix_pycrmkit_timeline_entries_event_type'), table_name='pycrmkit_timeline_entries')
    op.drop_index(op.f('ix_pycrmkit_timeline_entries_correlation_id'), table_name='pycrmkit_timeline_entries')
    op.drop_index(op.f('ix_pycrmkit_timeline_entries_actor_id'), table_name='pycrmkit_timeline_entries')
    op.drop_index('ix_pycrmkit_timeline_entity', table_name='pycrmkit_timeline_entries')
    op.drop_table('pycrmkit_timeline_entries')
    op.drop_index(op.f('ix_pycrmkit_tasks_status'), table_name='pycrmkit_tasks')
    op.drop_index(op.f('ix_pycrmkit_tasks_priority'), table_name='pycrmkit_tasks')
    op.drop_index(op.f('ix_pycrmkit_tasks_owner_id'), table_name='pycrmkit_tasks')
    op.drop_index(op.f('ix_pycrmkit_tasks_external_id'), table_name='pycrmkit_tasks')
    op.drop_index(op.f('ix_pycrmkit_tasks_due_at'), table_name='pycrmkit_tasks')
    op.drop_index(op.f('ix_pycrmkit_tasks_assignee_id'), table_name='pycrmkit_tasks')
    op.drop_table('pycrmkit_tasks')
    op.drop_table('pycrmkit_tags')
    op.drop_index('ix_pycrmkit_relationships_target', table_name='pycrmkit_relationships')
    op.drop_index('ix_pycrmkit_relationships_source', table_name='pycrmkit_relationships')
    op.drop_index(op.f('ix_pycrmkit_relationships_relationship_type'), table_name='pycrmkit_relationships')
    op.drop_table('pycrmkit_relationships')
    op.drop_table('pycrmkit_pipelines')
    op.drop_index(op.f('ix_pycrmkit_organizations_tax_id'), table_name='pycrmkit_organizations')
    op.drop_index(op.f('ix_pycrmkit_organizations_status'), table_name='pycrmkit_organizations')
    op.drop_index(op.f('ix_pycrmkit_organizations_registration_number'), table_name='pycrmkit_organizations')
    op.drop_index(op.f('ix_pycrmkit_organizations_owner_id'), table_name='pycrmkit_organizations')
    op.drop_index(op.f('ix_pycrmkit_organizations_legal_name'), table_name='pycrmkit_organizations')
    op.drop_index(op.f('ix_pycrmkit_organizations_archived_at'), table_name='pycrmkit_organizations')
    op.drop_table('pycrmkit_organizations')
    op.drop_index(op.f('ix_pycrmkit_custom_field_definitions_key'), table_name='pycrmkit_custom_field_definitions')
    op.drop_index(op.f('ix_pycrmkit_custom_field_definitions_active'), table_name='pycrmkit_custom_field_definitions')
    op.drop_index('ix_pycrmkit_custom_field_definition_key_revision', table_name='pycrmkit_custom_field_definitions')
    op.drop_table('pycrmkit_custom_field_definitions')
    op.drop_index(op.f('ix_pycrmkit_contacts_status'), table_name='pycrmkit_contacts')
    op.drop_index(op.f('ix_pycrmkit_contacts_owner_id'), table_name='pycrmkit_contacts')
    op.drop_index(op.f('ix_pycrmkit_contacts_archived_at'), table_name='pycrmkit_contacts')
    op.drop_table('pycrmkit_contacts')
    op.drop_index(op.f('ix_pycrmkit_communication_intents_status'), table_name='pycrmkit_communication_intents')
    op.drop_index(op.f('ix_pycrmkit_communication_intents_channel'), table_name='pycrmkit_communication_intents')
    op.drop_table('pycrmkit_communication_intents')
    op.drop_index(op.f('ix_pycrmkit_audit_entries_occurred_at'), table_name='pycrmkit_audit_entries')
    op.drop_index(op.f('ix_pycrmkit_audit_entries_correlation_id'), table_name='pycrmkit_audit_entries')
    op.drop_index(op.f('ix_pycrmkit_audit_entries_actor_id'), table_name='pycrmkit_audit_entries')
    op.drop_index(op.f('ix_pycrmkit_audit_entries_action'), table_name='pycrmkit_audit_entries')
    op.drop_index('ix_pycrmkit_audit_entity', table_name='pycrmkit_audit_entries')
    op.drop_table('pycrmkit_audit_entries')
    op.drop_index(op.f('ix_pycrmkit_activities_type'), table_name='pycrmkit_activities')
    op.drop_index(op.f('ix_pycrmkit_activities_occurred_at'), table_name='pycrmkit_activities')
    op.drop_index(op.f('ix_pycrmkit_activities_external_id'), table_name='pycrmkit_activities')
    op.drop_table('pycrmkit_activities')
    # ### end Alembic commands ###
