"""Optional FastAPI integration foundation for PyCRMKit."""

from pycrmkit.integrations.fastapi.dependencies import CRMDependency, CRMFactory
from pycrmkit.integrations.fastapi.errors import ErrorResponse
from pycrmkit.integrations.fastapi.pagination import (
    PageResponse,
    PaginationParams,
    pagination_params,
)
from pycrmkit.integrations.fastapi.schemas import (
    ActivityCreateRequest,
    ActivityParticipantSchema,
    ActivityResponse,
    ActivityUpdateRequest,
    AddressSchema,
    ContactCreateRequest,
    ContactEmailSchema,
    ContactPhoneSchema,
    ContactResponse,
    ContactUpdateRequest,
    EntityReferenceSchema,
    LeadConversionRequest,
    LeadCreateRequest,
    LeadResponse,
    OpportunityCreateRequest,
    OpportunityMoveRequest,
    OpportunityResponse,
    OrganizationAddressSchema,
    OrganizationCreateRequest,
    OrganizationDomainSchema,
    OrganizationResponse,
    OrganizationUpdateRequest,
    RelationshipCreateRequest,
    RelationshipEndpointSchema,
    RelationshipResponse,
    RelationshipUpdateRequest,
    TaskCreateRequest,
    TaskPriorityName,
    TaskResponse,
    TaskUpdateRequest,
    TimelineEntryResponse,
)

__all__ = [
    "ActivityCreateRequest",
    "ActivityParticipantSchema",
    "ActivityResponse",
    "ActivityUpdateRequest",
    "AddressSchema",
    "CRMDependency",
    "CRMFactory",
    "ContactCreateRequest",
    "ContactEmailSchema",
    "ContactPhoneSchema",
    "ContactResponse",
    "ContactUpdateRequest",
    "EntityReferenceSchema",
    "ErrorResponse",
    "LeadConversionRequest",
    "LeadCreateRequest",
    "LeadResponse",
    "OpportunityCreateRequest",
    "OpportunityMoveRequest",
    "OpportunityResponse",
    "OrganizationAddressSchema",
    "OrganizationCreateRequest",
    "OrganizationDomainSchema",
    "OrganizationResponse",
    "OrganizationUpdateRequest",
    "PageResponse",
    "PaginationParams",
    "RelationshipCreateRequest",
    "RelationshipEndpointSchema",
    "RelationshipResponse",
    "RelationshipUpdateRequest",
    "TaskCreateRequest",
    "TaskPriorityName",
    "TaskResponse",
    "TaskUpdateRequest",
    "TimelineEntryResponse",
    "pagination_params",
]
